# Generated by Django 5.0.1 on 2024-02-10 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=20)),
                ('type', models.CharField(max_length=20)),
                ('price', models.IntegerField()),
                ('year', models.DateField()),
            ],
        ),
    ]
