# Generated by Django 5.0.1 on 2024-03-13 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bikeapp', '0003_alter_bike_pimage_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='bike',
            name='details',
            field=models.CharField(default='', max_length=300),
        ),
    ]
