# Generated by Django 5.0.1 on 2024-03-13 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bikeapp', '0004_bike_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bike',
            name='details',
            field=models.CharField(default='', max_length=500),
        ),
    ]
